### 단일 표본 t 검정

In [1]:
with open('./datas/성인여성_키_데이터.txt', 'r') as f:
    data = f.read().split('\n')
    data = list(map(float, data))

In [2]:
data[:3]

[150.27, 142.94, 160.99]

In [3]:
from scipy.stats import *
kstest(data, 'norm')
# 정규분포를 따르는지 테스트
# p-value가 < 0.05로 정규성을 띈다고 볼 수 있음
# 정규성을 띈다

KstestResult(statistic=1.0, pvalue=0.0, statistic_location=137.5, statistic_sign=-1)

In [5]:
print(ttest_1samp(data, 163))
# M = 163
# pvalue가 0.05미만이므로 영가설을 기각
# 평균값이 163보다 작다 (통계량이 음수이므로)
# 양수라면 163보다 큰 값

TtestResult(statistic=-2.979804412662668, pvalue=0.006510445335847954, df=24)


### 독립 표본 t검정

In [7]:
import pandas as pd
import numpy as np

In [9]:
df1 = pd.read_csv('./datas/반별_점수_type1.csv', encoding='euc-kr')
df1.head()

반  점수
0  A  73
1  A  69
2  A  71
3  A  71
4  A  73

In [10]:
group_A = df1['점수'].loc[df1['반'] == 'A'].values
group_B = df1['점수'].loc[df1['반'] == 'B'].values

print(group_A)
print(group_B)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63 56 73 61 55 77 75 65 61 55]


### kstest를 이용한 정규성 검정

In [11]:
print(kstest(group_A, 'norm'))
print(kstest(group_B, 'norm'))

KstestResult(statistic=1.0, pvalue=0.0, statistic_location=58, statistic_sign=-1)
KstestResult(statistic=1.0, pvalue=0.0, statistic_location=55, statistic_sign=-1)


### 등분산 검정

In [12]:
levene(group_A, group_B)

LeveneResult(statistic=2.033067087400979, pvalue=0.164964086222101)

In [13]:
np.var(group_A, ddof=1)

32.26052631578948

In [14]:
np.var(group_B, ddof=1)

68.54444444444445

### 독립표본 t-검정

In [15]:
print(ttest_ind(group_A, group_B, equal_var=True))

TtestResult(statistic=2.5128526794964134, pvalue=0.01801095352893767, df=28.0)


### Tip. 다른 포맷의 데이터 처리

In [18]:
df2 = pd.read_csv('./datas/반별_점수_type2.csv', encoding='euc-kr')
df2.head()

A반    B반
0  73  63.0
1  69  56.0
2  71  73.0
3  71  61.0
4  73  55.0

In [21]:
group_A = df2['A반'].dropna().values
group_B = df2['B반'].dropna().values

In [22]:
print(group_A)
print(group_B)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63. 56. 73. 61. 55. 77. 75. 65. 61. 55.]
