### 벡터와 행렬, 연산

### 필요한 패키지 로딩

In [12]:
import numpy as np 
import scipy
import matplotlib
from scipy import linalg as la 
import matplotlib.pyplot as plt

In [13]:
print(np.__version__)
print(scipy.__version__)
print(matplotlib.__version__)

1.26.4
1.13.1
3.9.2


### 벡터 표현
- 벡터는 순서가 있는 숫자들의 목록, 1차원 배열

In [14]:
a = [0.6, 0.93, 0.24, 0.27]

In [15]:
v = np.array(a)
v

array([0.6 , 0.93, 0.24, 0.27])

In [16]:
v[1]

0.93

In [17]:
type(v[1])

numpy.float64

### 벡터의 크기
- size, lengh : 벡터의 원소 개수를 의미
- dimension : 벡터의 차원

In [19]:
v.shape

(4,)

In [20]:
v.size

4

In [21]:
len(v)

4

In [22]:
v.ndim

1

### 부분 벡터의 생성

In [24]:
v_sub = v[0:2]
v_sub

array([0.6 , 0.93])

### 특별한 벡터
- 영 벡터 : 모든 원소가 0인 벡터

In [25]:
size = 3
zeros = np.zeros(shape=(size,))
zeros

array([0., 0., 0.])

- 단위벡터 : 하나의 원소만 1이고 나머지는 모두 0인 벡터

In [26]:
e = np.zeros(shape=(size,))
e

i = 1
e[i] = 1
e

array([0., 1., 0.])

- 1 벡터 : 모든 원소가 1인 벡터

In [27]:
one = np.ones(shape=(size,))
one

array([1., 1., 1.])

### 벡터의 연산
- 벡터의 덧셈 : 크기가 같은 2개의 벡터의 덧셈은 대응 원소의 합으로 정의

In [28]:
a = np.array([1,3])
b = np.array([3,1])
a + b

array([4, 4])

- 교환 법칙

In [30]:
a+b

array([4, 4])

In [31]:
b+a

array([4, 4])

In [32]:
a + b == b + a

array([ True,  True])

- 결합 법칙

In [33]:
d = np.array([1,2])

In [34]:
(a + b) + d

array([5, 6])

In [35]:
a + (b + d)

array([5, 6])

In [36]:
(a + b) + d == a + (b + d)

array([ True,  True])

- 벡터의 뺄셈

In [38]:
a = np.array([3,1])
b = np.array([1,3])
b - a

array([-2,  2])

- 스칼라-벡터 곱

In [39]:
alpha = 1/2
a = np.array([2,3])
alpha * a

array([1. , 1.5])

In [40]:
a * alpha

array([1. , 1.5])

- 스칼라 곱의 교환 법칙

In [43]:
alpha * a == a * alpha

array([ True,  True])

- 스칼라 곱의 분배 법칙

In [44]:
beta = 0.7
a = np.array([2,3])
(alpha + beta) * a

array([2.4, 3.6])

In [45]:
alpha * a + beta * a

array([2.4, 3.6])

In [46]:
(alpha + beta) * a == alpha * a + beta * a

array([ True,  True])

### 내적

- 내적 계산 또는 점적

In [47]:
a = np.array([-1,2,3])
b = np.array([1,-2,4])

In [57]:
a * b
a * b.T
a.T * b

array([-1, -4, 12])

In [49]:
np.sum(a*b)

7

In [50]:
np.inner(a,b)

7

In [51]:
np.dot(a,b)

7

### 행렬 연산
- '*' : 행렬의 성분 별로 곱하기
    => 두 행렬의 shape이 동일해야 함
- '@' : matrix multiplication, 행과 열을 곱해서 서로 더하기
    => A, B : A행렬의 열과 B행렬의 행이 동일해야 함

- 내적의 성질

In [53]:
a = np.array([-1,2,3])
b = np.array([1,-2,4])

print(np.dot(a,b))
print(np.dot(b,a))

print(np.dot(a,b) == np.dot(b,a))

7
7
True


- 내적의 결합 법칙

In [54]:
alpha = 0.5
np.dot(alpha * a, b) == alpha * np.dot(a, b)

True

- 내적의 분배 법칙

In [55]:
c = np.array([1,2,3])
np.dot(a+b,c) == np.dot(a,c) + np.dot(b,c)

True

- 내적의 활용

In [58]:
a = np.array([1,2,3])
size = len(a)
ones = np.ones(shape=(size,))

print(a)
print(ones)

np.dot(ones, a)

[1 2 3]
[1. 1. 1.]


6.0

In [59]:
np.dot(ones, a) / len(a)

2.0

In [60]:
np.dot(a, a)

14

### 벡터 노름
- norm : 수학적 개념에서 벡터 공간 내에서 길이 또는 크기를 정의하는 규칙
- 벡터의 유클리디안 노름 계산 : 원점에서 얼마만큼 떨어져 있는지 계산하는 방식

In [61]:
from scipy import linalg as la 

In [62]:
round(np.sqrt(np.sum(a.T * a)),3)

3.742

In [63]:
a = np.array([2,3])
la.norm(a).round(3)

3.606

In [64]:
a = np.array([-1,2,3])
b = np.array([1,-2,4])

beta = 0.5
la.norm(beta * a) == np.abs(beta) * la.norm(a)

True

In [65]:
la.norm(a + b) <= la.norm(a) + la.norm(b)

True

In [66]:
la.norm(a) >= 0

True

### 2차원 행렬

In [72]:
b = np.array([[1,2], [3,4], [5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
b.shape

(3, 2)

In [74]:
b = np.array([[1,2], [3,4], [5,6], [7,8]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
b.shape

(4, 2)

In [80]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
b.shape

(3, 4)

In [83]:
a = np.arange(0, 5, 0.5, dtype=int)
b = np.arange(-3, 3, 0.5, dtype=int)
print(a)
print(b)

[0 0 0 0 0 0 0 0 0 0]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]


In [84]:
a = np.arange(0, 5, 0.5, dtype=float)
b = np.arange(-3, 3, 0.5, dtype=float)
print(a)
print(b)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5]


In [85]:
a = np.arange(0, 5)
b = np.arange(-3, 3)
print(a)
print(b)

[0 1 2 3 4]
[-3 -2 -1  0  1  2]


In [90]:
a = np.arange(12).reshape(3,4)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [93]:
a = np.arange(12).reshape(-1,4) # -1 : 알아서 니가 알맞게 넣어
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
a = np.arange(12).reshape(3,-1) # -1 : 알아서 니가 알맞게 넣어
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [95]:
a[2][3]

11

In [97]:
for i in range(3):
    print(a[i][0])

0
4
8


In [98]:
a[:,0]

array([0, 4, 8])

In [99]:
a[:,-1]

array([ 3,  7, 11])

In [100]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

@ == np.dot() / 2차원까지만

In [106]:
a = np.array([[1,2],[2,3]]) # (2,2)
b = np.array([[2,3,4], [4,5,6]]) # (2,3)
c = a@b
c

print(c)
print(np.dot(a,b))

[[10 13 16]
 [16 21 26]]
[[10 13 16]
 [16 21 26]]


In [107]:
c.shape

(2, 3)

### 정규직교 벡터

In [67]:
a1 = np.array([0,0,1]).reshape(-1,1)
a1

array([[0],
       [0],
       [1]])

In [ ]:
a2 = 1/np.sqrt(2)